import AppKit
import ClapCore
import os

/// Polls NSPasteboard.general.changeCount every 150 ms on a background task
/// and captures new text/images into the store. All work happens off the
/// main thread (except the cheap frontmost-app lookup).
///
/// Security: clipboard content is never logged. Metadata only.
actor PasteboardMonitor {

    private let store: ClipboardStore
    private let logger = Logger(subsystem: "com.spongycode.clap", category: "monitor")

    private var pollTask: Task<Void, Never>?
    private var lastChangeCount: Int

    // Cached config, refreshed on configChanged notifications.
    private var paused = false
    private var exclusions: Set<String> = []

    // Set right before clap itself writes to the pasteboard: the next change
    // is treated as self-inflicted and only bumps recency of this entry.
    // After the write, the copy path confirms the changeCount it produced so
    // a foreign copy that lands in the same 150 ms poll window (observed
    // count > confirmed count) is still captured instead of swallowed.
    private var pendingSelfEntryID: Int64?
    private var confirmedSelfChangeCount: Int?

    // The very first poll captures whatever is already on the pasteboard, so
    // content copied just before launch isn't silently swallowed by the
    // changeCount baseline taken in init.
    private var firstPoll = true

    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    init(store: ClipboardStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard pollTask == nil else { return }
        pollTask = Task(priority: .utility) { [weak self] in
            while !Task.isCancelled {
                await self?.poll()
                try? await Task.sleep(nanoseconds: Timing.pasteboardPollNanos)
            }
        }
        logger.info("pasteboard monitor started")
    }

    func stop() {
        pollTask?.cancel()
        pollTask = nil
    }

    /// Called by the copy path right before clap writes to the pasteboard.
    func expectSelfChange(entryID: Int64) {
        pendingSelfEntryID = entryID
        confirmedSelfChangeCount = nil
    }

    /// Called by the copy path right after writing, with the changeCount the
    /// write produced.
    func confirmSelfChange(changeCount: Int) {
        guard pendingSelfEntryID != nil else { return }
        confirmedSelfChangeCount = changeCount
    }

    /// Re-reads monitoring.paused and exclusions from the config table.
    func refreshConfig() async {
        paused = ((try? await store.config(ConfigKey.monitoringPaused)) ?? "0") == "1"
        var ids: Set<String> = []
        if let raw = (try? await store.config("exclusions")) ?? nil,
           let data = raw.data(using: .utf8),
           let array = try? JSONDecoder().decode([String].self, from: data) {
            ids = Set(array)
        }
        exclusions = ids
        logger.debug(
            "config refreshed: paused=\(self.paused, privacy: .public), exclusions=\(self.exclusions.count, privacy: .public)")
    }

    // MARK: - Poll loop

    private func poll() async {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        let isFirstPoll = firstPoll
        firstPoll = false
        guard changeCount != lastChangeCount || isFirstPoll else { return }
        lastChangeCount = changeCount

        // Our own write: only bump recency, never re-capture. If a foreign
        // copy landed after ours within the same poll window, the observed
        // count exceeds the confirmed one — bump our entry but fall through
        // so the foreign content is captured too.
        if let entryID = pendingSelfEntryID {
            pendingSelfEntryID = nil
            let confirmed = confirmedSelfChangeCount
            confirmedSelfChangeCount = nil
            try? await store.touch(id: entryID)
            if confirmed == nil || changeCount <= confirmed! {
                IPC.post(.storeChanged)
                return
            }
        }

        // Distributed configChanged notifications can lag behind `clap
        // pause`/`clap resume`; a stale cached flag here would silently drop
        // the capture. Changes are rare, so re-reading config per change is
        // cheap insurance.
        await refreshConfig()
        guard !paused else { return }

        let sourceApp = await MainActor.run {
            NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        }
        if let sourceApp, exclusions.contains(sourceApp) { return }

        let types = pasteboard.types ?? []
        if types.contains(where: { Self.skippedTypes.contains($0.rawValue) }) { return }

        do {
            var captured = false
            if let string = pasteboard.string(forType: .string) {
                captured = try await store.captureText(string, sourceApp: sourceApp) != nil
            } else if types.contains(.png), let data = pasteboard.data(forType: .png) {
                captured = try await store.captureImage(data: data, format: "png", sourceApp: sourceApp) != nil
            } else if types.contains(.tiff), let data = pasteboard.data(forType: .tiff) {
                captured = try await store.captureImage(data: data, format: "tiff", sourceApp: sourceApp) != nil
            }
            if captured {
                IPC.post(.storeChanged)
            }
        } catch {
            // Metadata only — never the clipboard content itself.
            logger.error("capture failed: \(String(describing: error), privacy: .public)")
        }
    }
}
